name: build

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.cfg.cc }} (${{ matrix.cfg.build_type }})
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { cc: gcc,   cxx: g++,     build_type: Debug   }
        - { cc: gcc,   cxx: g++,     build_type: Release }
        - { cc: clang, cxx: clang++, build_type: Debug   }
        - { cc: clang, cxx: clang++, build_type: Release }

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        mkdir -p ${{runner.workspace}}/build
        git submodule init
        git submodule update

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.cfg.build_type }}
      env: 
        CC:  ${{ matrix.cfg.cc }}
        CXX: ${{ matrix.cfg.cxx }}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build .

    - name: Run tests
      working-directory: ${{runner.workspace}}/build/tests
      shell: bash
      run: ./mu_tests --gtest_brief=1