name: cmake

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{runner.workspace}}/build
        git submodule init
        git submodule update

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G "Unix Makefiles"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build .

    - name: Generate coverage report
      working-directory: ${{runner.workspace}}/coverage
      shell: bash
      run: bash coverage_llvm.sh

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./text_llvm/index.txt
        fail_ci_if_error: true