name: coverage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        shell: bash
        run: |
          git submodule init
          git submodule update
          sudo apt-get install -y llvm
          mkdir -p build

      - name: Generate coverage report
        shell: bash
        run: |
          cd coverage/
          bash coverage_llvm.sh

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./text_llvm/index.txt
          fail_ci_if_error: true